### ISSUE TITLE
Fontsampler not fully loading, preventing load of page

### ISSUE THREAD

**Issue by Vereschagin** [kontur/fontsampler-wordpress-plugin#104]
Hi, Johannes:

There seems to be a problem with version 0.2.6 of the plugin. The fontsampler will not completely load and its failure to load prevents the rest of the page from loading. See my screenshot below which shows the page with an unloaded fontsampler in Safari (10.1.1), with the end of the page code displayed in the web inspector. Page loading stops at line 179. The same problem occurs in Chrome (59.0.3071.115). This is with WP 4.8, but was also happening with 4.7. 

Any clues?

![2017_07_12](https://user-images.githubusercontent.com/10108357/28118867-d5776428-66e0-11e7-9e00-9381d9e28f02.png)

**Comment by kontur** [comment]
Can you temporarily add the line `define( 'WP_DEBUG', true );` ([info](https://codex.wordpress.org/WP_DEBUG)) to your wp-config.php to display the PHP error that is causing this? If reloading the page after that doesn't show anything different, please also add a line of `error_reporting(E_ALL)` right after the opening `<?php ` of your wp-config.php.

Please let me know what error messages come up, either on the page or in the source code, or let me know and I'll check back on the site itself. Also, what version of PHP are you using? Fontsampler needs at least PHP 5.6 or higher, as in fact Wordpress itself recommends as well.

**Comment by Vereschagin** [comment]
My hosting provider was running 5.5.10 as default. I updated to 5.6 and the display problem is fixed. Thanks!

**Comment by kontur** [comment]
Great, I've already opened #100 previously, which is to implement a simply check for this and displaying an plugin-wide error message pointing it out for installations with PHP versions that don't satisfy the requirement.
