### ISSUE TITLE
Selected OT features get deselected when switching fonts

### ISSUE THREAD

**Issue by kontur** [kontur/fontsampler-wordpress-plugin#120]
> When you check an OT feature in the OT dropdown panel — for example Old Style Figures.
> 
> — then select another font style in the drop down
> — all previous OT feature selections (in example case Old Style Figures) are deselected
> — when you try to select them once more they don’t work
> — when you deselect them they start to work in the new font style

**Comment by Vereschagin** [comment]
Confirmed. I was going to report this. Thanks!

**Comment by kontur** [comment]
Thanks for your input @Vereschagin 

Will investigate solution for this one this week.
