### ISSUE TITLE
OT panel button class

### ISSUE THREAD

**Issue by lettersoup** [kontur/fontsampler-wordpress-plugin#121]
— When the OT Button is clicked (opened) you have a class: font sampler-multiselect-selected
— When the OT panel is closed by clicking the OT button this class is off
— but when you close the OT panel by clicking outside the dropdown this class is still on. 

These causes problems with the styling of the OT button. 

Kind regards,
Botio

**Comment by kontur** [comment]
Fixed in 0.3.8 now live.
