### ISSUE TITLE
Some fonts are not loading

### ISSUE THREAD

**Issue by shahabsiavash** [kontur/fontsampler-wordpress-plugin#127]
Hi,

I just put some of my fonts on my site. In one case which a font has 12 styles, weirdly some of them are loading instead of each other. I mean the first one supposed to be regular, but it is the Italic one which is the second font in the list. Also some of other ones are also missing. I don't know why?

![image](https://user-images.githubusercontent.com/20119395/32149982-b5c8e998-bd21-11e7-87d7-2e994eaf5ee5.png)

You can see all 12 of them with different filenames. And now if you go to this link and find the Fontsampler, you can see some of them are missing:
https://shahabsiavash.com/?p=1256

**Comment by kontur** [comment]
Just for reference: When I visit the page I get redirected to [this page](https://shahabsiavash.com/%D8%AE%D8%B1%DB%8C%D8%AF-%DB%B1%DB%B2-%D9%81%D9%88%D9%86%D8%AA-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%D9%88-%D9%84%D8%A7%D8%AA%DB%8C%D9%86-%DA%A9%DB%8C%D8%AE%D8%B3%D8%B1%D9%88/) - is that the page you linked, it seems like it's the "homepage", no?

On that page I don't get any console messages about missing fonts. There is 12 different styles of DEMOKayKhosrow... loading. Seeing the names of the files, I need to point out one issue with Fontsamplers that have several files with same PostScript Family Name as well as Weight - Fontsampler relies on CSS and CSS does not define an "outline" or "stencil" style - i.e. if both "regular", "outline" and "stencil" have the same weight and family name (but look visually different or are different files) Fontsampler still cannot tell them apart. The only workaround for this is to include the style name in the Family Name of the woff you are generating.

**Comment by shahabsiavash** [comment]
Yes, that was the correct page. As I said they all were loaded but were not showing. So I checked and you were right, some of them had identical names. Thanks. It is solve now :)
