### ISSUE TITLE
Where is Fontsampler data stored?

### ISSUE THREAD

**Issue by shahabsiavash** [kontur/fontsampler-wordpress-plugin#136]
Hi,
My host provider decided to do a server upgrade. So after that my site went down, because the database got deleted in the process!! And after a lot of tickets they only blame Plesk. So not going to bore you with this, but no backup or database import did work. Until finally I gave them the Dropbox backup and they could restore it. I went through a nightmare and the other one is here: All fontsets and fontsamplers are gone now! I got this:
`The typesamplers with ID 17 can not be displayed because some files or the type sampler set are missing! You are seeing this notice because you have rights to edit posts - regular users will see an empty spot here.
`
![image](https://user-images.githubusercontent.com/20119395/36898504-58c9145a-1e30-11e8-9e71-b799573cd2de.png)

I have checked the fonts are there.
And they are a lot of them! How come we restored everything and yet all Fontsampler data is gone? Where the plugin data is stored? Please help!

**Comment by kontur** [comment]
Hey,

Fontsampler stores all data in the same database as the rest of Wordpress, but in custom tables that are next to your other standard Wordpress tables like wp_posts etc. By default (assuming the standard wp_ prefix) those tables are:

- wp_fontsampler_fonts
- wp_fontsampler_sets
- wp_fontsampler_sets_x_fonts
- wp_fontsampler_settings

It is quite common for Wordpress plugins to create their own tables in the database, at least if the structure of the data does is not a good fit for using the standard post or postmeta tables. Did you lose any other data in the restoring from backup?

Does your host have an actual full backup your database? (They should, if they fail with an update like this and lose your data on top of that!)
How did you create your own Wordpress backups, with a plugin, and if so with which, or the export tool?

My guess at this point is that the backup you have exported only standard Wordpress tables, not the entire database of your Wordpress installation, thus missing all the actual data (not the fonts, those are files and as you save you have them separately) and configuration of your Fontsamplers.

Hopefully this helps you figure out and find a working backup!

**Comment by kontur** [comment]
I changed the issue title to reflect that it is not, in fact, the plugin that is losing the data, but more generally an issue of where the plugin's data is located at.

**Comment by shahabsiavash** [comment]
Thanks for the reply. My backup was a full host backup and not just a Wordpresw backup. So it includes everything, such as apache files, conf, emails, subdomains, and databases and files.

So now I am checking, but other plugins are doing just fine. And the weird part is I can see your tables in my backup database file! So they are there apparently!

I don't know what should I do now!

![1520008366372-454210449](https://user-images.githubusercontent.com/20119395/36910033-e0056abc-1e54-11e8-82f9-0aed279381f6.jpg)

**Comment by shahabsiavash** [comment]
Yes since morning. They are there. I don't know if they're empty or full. But I can see them. Still there is no sets or fonts in the plugin :(

![image](https://user-images.githubusercontent.com/20119395/36913232-8000b4b4-1e5e-11e8-8b8f-75dad6de6d74.png)

**Comment by kontur** [comment]
Can you see if there is content in the tables? It might be the tables were created empty when you reinstalled your backup, for the plugin it would have seemed like a "new install".

In your backup, do you have a .sql file with the database? If so, can you find any INSERT INTO ... statements with the Fontsampler tables?

**Comment by shahabsiavash** [comment]
I'm not an expert in this area. But it seems they are all empty. I didn't do a "new install." I'm sorry, but it should be a problem with Fontsampler. Because as I said this was a full backup. Everything is back. All plugins, widgets, comments, settings.

Fontsampler didn't even save the settings that I have changed months ago like the default text for the sampler or the right to left option in the basic section of the Fontsampler or even the default text alignment. 

**Is there any way that I could import the data that must have been saved somewhere (because it was working until 2 days ago) and add them to the new database?**

It is very frustrating to add all those settings and font files and fontsets again.

**Comment by kontur** [comment]
Okay, like I said, probably when reinstalling from the backup for the plugin it seemed like a "fresh" install, so it started with empty tables. You can import them from your backup.

> In your backup, do you have a .sql file with the database? If so, can you find any INSERT INTO ... statements with the Fontsampler tables?

You want to take only those Fontsampler specific INSERT statements to import them in your database. If you have those database backups and they contain the Fontsampler tables it is certainly possible to restore them.

**Comment by shahabsiavash** [comment]
No I don't. It is a .gz file with a -db file in it. So no way? And this would happen every time the plugin gets disabled or something like this happens?

**Comment by kontur** [comment]
You mean it's a .db extension? Look at the actual text content of that file in a file editor, does it have INSERT INTO or other SQL statements?

What I am saying is that when the plugin gets installed it will automatically create the tables. It is likely that in your restoring your backup somehow the plugin was activated, but the database tables not restored yet and then missing, which will result in the plugin assuming a new install and setting up the required database tables. Again, if you have a full database backup, one way or another, the Fontsampler tables are there and can be imported after the fact.

**Comment by shahabsiavash** [comment]
Hi again and thanks for the replies.
Yes there are a lot of INSERT INTOs. Actually some of them are related to Fontsampler as I see it:
![image](https://user-images.githubusercontent.com/20119395/36925834-0395a822-1e8a-11e8-9f28-f6a94978e1fc.png)

I don't know why they didn't imported then!

**Comment by kontur** [comment]
Hey,
not really sure why they didn't import, but you should be able to get the data from there.

You can copy the INSERT INTO lines pertaining to the Fontsampler tables I mentioned above and in phpMyAdmin paste them into the SQL tab and run them (one time!). Again, be sure to make a full database backup before doing anything, or running this first on a development setup.

**Comment by shahabsiavash** [comment]
Thanks. That would be something like this?

![image](https://user-images.githubusercontent.com/20119395/36933722-54aa93f8-1ef3-11e8-999c-eb4a208babc7.png)

Sorry. I don't know about this stuff and very pessimist about any changes that could bring down the site!

**Comment by kontur** [comment]
Yes, that looks about right, but also you need all four Fontsampler tables / Insert statements, since they reference each other.

Again, please take a FULL BACKUP OF THE ENTIRE DATABASE before doing anything and ideally try this operation on a development version of your site before trying it on your live site.

**Comment by shahabsiavash** [comment]
Good news! I told them about that and they agreed to do the import. Because you know it was their fault in the beginning. So now they are all imported and working.

Would you please look into this? Why this happened and all that?
Because I vaguely remember that once I disabled the Fontsampler and all the fontsets were gone too. It was a long time ago and there weren't too many of them, so I've created them again. It seems something worth considering to me. You can check that in a test area I guess.

**Comment by kontur** [comment]
Did you manage to reinstate the full working backup?

I'll double check that plugin disabling does not remove anything. Uninstalling a plugin, however, is supposed to remove any data associated with it — otherwise that data would lay around on the server or database indefinitely.

**Comment by kontur** [comment]
Closing this issue as not relating to the Plugin code.
