### ISSUE TITLE
HELP!!! SyntaxError: The string did not match the expected pattern. Safari is not displaying one font sampler. 

### ISSUE THREAD

**Issue by TanyaRunyan76** [kontur/fontsampler-wordpress-plugin#161]
I have two samplers on one page. One works great, you can see the controls the other you don't see anything. They have the exact same settings, one is cursive fonts the other is print fonts. https://www.runwildlittleone.com/font-sampler/

**Comment by TanyaRunyan76** [comment]
![Screen Shot 2019-08-19 at 10 47 20 PM](https://user-images.githubusercontent.com/54299721/63316104-5e731880-c2d3-11e9-9cbd-b90ac3c3128f.png)

**Comment by TanyaRunyan76** [comment]
![Screen Shot 2019-08-19 at 10 48 55 PM](https://user-images.githubusercontent.com/54299721/63316146-8f534d80-c2d3-11e9-9992-3ea2a6d3633a.png)

**Comment by TanyaRunyan76** [comment]
I went ahead and deleted the 3 fonts that "can't load" and I can now see the second sampler, HOWEVER, It still doesn't display on safari only Chrome. The above errors are for chrome.

**Comment by TanyaRunyan76** [comment]
I have tried to view it on Chrome on my iPhone XR using both Safari and Chrome and ONE of the font samplers is not viewing on both search engines. Software is up to date.

**Comment by TanyaRunyan76** [comment]
Here is the error from Safari 
![Screen Shot 2019-08-20 at 8 12 09 PM](https://user-images.githubusercontent.com/54299721/63394876-54125680-c387-11e9-9c3d-71d947b10a11.png)

**Comment by kontur** [comment]
Hey, sorry for the late reply, good to see you made some progress already debugging this further from the initial issue.

What version of Safari are you using?
