### ISSUE TITLE
Text doesn't appear

### ISSUE THREAD

**Issue by PierreFave** [kontur/fontsampler-wordpress-plugin#162]
Hello! 
I have an issue with the font sampler.
I create a default text in the basic settings, but it doesn't appear on my page on the website.
It just appear when I type text directly on the web page in the font tester…
Is there any way to fix it ?

Thx!

Pierre

<img width="1477" alt="Capture d’écran 2019-12-05 à 15 43 14" src="https://user-images.githubusercontent.com/34349933/70245271-168adb00-1776-11ea-8b92-1c5f6dc47cb3.png">
<img width="927" alt="Capture d’écran 2019-12-05 à 15 43 29" src="https://user-images.githubusercontent.com/34349933/70245275-17237180-1776-11ea-8145-dd5ca5739593.png">
<img width="880" alt="Capture d’écran 2019-12-05 à 15 43 53" src="https://user-images.githubusercontent.com/34349933/70245276-17237180-1776-11ea-90ce-5e1804653319.png">

**Comment by kontur** [comment]
Hmm. Hard to say what is the root cause for this. 
Is the page online and could you link to it?
Do you get any javascript erros in the developer console when loading the page?

**Comment by PierreFave** [comment]
Sorry, I just didn’t understand quite well the ui logic of the plugin. It’s fixed now!

Thanks 

Envoyé de mon iPhone

**Comment by kontur** [comment]
Okay :)

If you don't mind explaining, what was the thing that was confusing or didn't work like you expected it? Maybe it can be improved in the future.
