### ISSUE TITLE
TypeError on Chrome and Firefox

### ISSUE THREAD

**Issue by eggplantPrince** [kontur/fontsampler-wordpress-plugin#163]
Hi!

I'm using FontSampler with  woocommerce . I call the do_shortcode through a php template of a product, and i can see font sampler creating it's elements, but nothing gets displayed. In the console i get the error:

`TypeError: m.dataset.fonts is undefined (fontsampler.js:117:106)
    p http://localhost/wp-content/plugins/fontsampler/js/fontsampler.js?ver=5.3.2:117
    <anonymous> http://localhost/wp-content/plugins/fontsampler/js/fontsampler.js?ver=5.3.2:117
    execCb http://localhost/wp-content/plugins/fontsampler/js/fontsampler.js?ver=5.3.2:109
    check http://localhost/wp-content/plugins/fontsampler/js/fontsampler.js?ver=5.3.2:109
    enable http://localhost/wp-content/plugins/fontsampler/js/fontsampler.js?ver=5.3.2:109
    init http://localhost/wp-content/plugins/fontsampler/js/fontsampler.js?ver=5.3.2:109
    a http://localhost/wp-content/plugins/fontsampler/js/fontsampler.js?ver=5.3.2:109`

i added the filter 
`add_filter('fontsampler_enqueue_styles',true);`

i also echoed the exact string of the shortcut and it's according to the docs.
`echo('[fontsampler id='.$fs_id .']');`
outputs
`[fontsampler id=1]`

EDIT: when using [fontsampler id=1] through the visual editor of a word press page it loads correctly.

**Comment by kontur** [comment]
What's the actual html output to the page a) when used with a shortcode b) when used with `do_shortcode`? It looks like it's not getting any font files passed in.

**Comment by eggplantPrince** [comment]
heres a test with the ubuntu font

[fontsampler_htmloutput.txt](https://github.com/kontur/fontsampler-wordpress-plugin/files/4104355/fontsampler_htmloutput.txt)

**Comment by eggplantPrince** [comment]
I figured it out. i had a div with the a fontsampler-wrapper class surrounding it.

**Comment by kontur** [comment]
Okay, great that you could solve it, thanks for keeping me in the loop 👍
