### ISSUE TITLE
Font Sampler display default font.

### ISSUE THREAD

**Issue by sstw83** [kontur/fontsampler-wordpress-plugin#164]
Hi

I recently uploaded a font into my Font Sampler.
In the admin section, the font preview is showing the correct font.
![1](https://user-images.githubusercontent.com/60577508/73611245-d8495500-461a-11ea-859e-621754525d8b.jpg)

However, when I check it on my website page, it is displaying default font. It only happens on this particular font, other fonts do not have this issue.
![2](https://user-images.githubusercontent.com/60577508/73611250-db444580-461a-11ea-8b4f-2c76dbffa0fe.jpg)

Hopefully you can help me out with this issue. 

Thank you 😉

**Comment by kontur** [comment]
Can you see if the developer console outputs any warnings or errors, or could you link me to the page? Is this a font you made yourself or downloaded from somewhere?

**Comment by sstw83** [comment]
Hi

Thank you for your reply.
Sorry, can I know how to see the developer console outputs?

I downloaded this font from this website.
https://www.1001freefonts.com/weather-sunday.font

This is my product page, font style#1
https://www.alskar.co/products/plush-pencil-case-personalized-birthday-gifts/


Thank you,
Wei Siang

**Comment by kontur** [comment]
Hey,

Font style #1 seems to render ok for me? Could it be that is a caching issue, have you tried clearing your browser cache and refreshed the page?




Developer tools can be accessed either by some main menu or many browsers have a right-click “inspect element” entry to view more details. The view that opens should have a “console” tab; but on the site I see nothing problematic.

Best,
Johannes
_________
Johannes Neumeier
Designer ∞ Developer
https://johannesneumeier.com
hello@johannesneumeier.com
+358 50 536 1961

**Comment by sstw83** [comment]
Hi Johannes,

I have cleared my browsers and website cache. However different browsers
return with different result.

Firefox - the font display correctly
Google Chrome - display in default font
Microsoft Edge - ok
Safari - ok
Opera - in default font

I am not too sure what is happening here.

**Comment by kontur** [comment]
Hey,

you really should be using only .woff files for the previews. ttf files (the other fonts) are kind-of supported, but the first file is a .otf file and that is why it won't render in some browsers (that do a bit more strict checks).

Note also that using "personal use" fonts on a commercial site will get you into trouble before long. Since you already need woff files anyway, I suggest you use the opportunity and purchase a webfont license for that first (and the possible other) fonts in your tester.
