### ISSUE TITLE
font style linking does not work 

### ISSUE THREAD

**Issue by lettersoup** [kontur/fontsampler-wordpress-plugin#167]
Hi, 
we just updated to WordPress 5.4.1
Since the update the font style linking in Font Sampler does not work any more. 
The style names are no longer visible, also changing the styles does not work. Could you please advise on that. Тhe bug appears in version 0.4.5 ( in version 0.4.4 everything still works fine) Here is a screenshot of the bug:
<img width="1399" alt="Bildschirmfoto 2020-05-12 um 15 10 16" src="https://user-images.githubusercontent.com/6229652/81716256-74d08e00-9479-11ea-8556-b91eaa2f14a4.png">

You can also check it on our dev site:
https://dev.lettersoup.de/product-category/quasimoda/

**Comment by kontur** [comment]
Thanks for reporting.

After a quick glance it looks like using a hyphen in the font name (overwrite) breaks the parsing in the font list and uses only the first part (e.g. the "family" of the "family-style" string) thus all styles have the same name and switching them does not work.

I'll investigate more now and see about a fix.

**Comment by kontur** [comment]
I just released version `0.4.9` to the Wordpress plugin directory. Please update the plugin and test with that version and let me know if that solves the issue.

**Comment by lettersoup** [comment]
Many thanks for tue quick update! Version 0.4.9 works fine.

**Comment by kontur** [comment]
Super Sache, thanks for confirming the fix works.
