### ISSUE TITLE
can't see anything on the website

### ISSUE THREAD

**Issue by r1rider01** [kontur/fontsampler-wordpress-plugin#171]
The font sampler doesn't seem to be loading on the user end....

![image](https://user-images.githubusercontent.com/3099177/94494078-e05e9200-01b3-11eb-9471-77387efe3db2.png)
![image](https://user-images.githubusercontent.com/3099177/94494107-f5d3bc00-01b3-11eb-823d-3dd6d11b1f0d.png)
Code appears, but nothing shows.

WP 5.5.1
Using GOYA theme

Disabled alot of plugins, but still didn't work.

My site is set to Offline mode, so can't really give a URL

**Comment by kontur** [comment]
Can you look in the developer tools console of your browser. Are there any errors or warnings output when you reload the page with the fontsampler on it?

**Comment by r1rider01** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/3099177/94568987-d16af480-0232-11eb-99ee-545c9f2a2243.png)

**Comment by r1rider01** [comment]
ummm... nevermind, I used woff2  and otf files, on the back end they loaded just fine, but the front end they caused the errors above.    uploaded a standard woff file.   everything works!

Thanks.
