### ISSUE TITLE
Code appears in page text.

### ISSUE THREAD

**Issue by DunwichType** [kontur/fontsampler-wordpress-plugin#20]
Fontsampler code is appearing on pages as text. This is what I see when I set up Fontsampler on a clean install of Wordpress with the default theme.
<img width="865" alt="screen shot 2016-10-25 at 10 45 08 am" src="https://cloud.githubusercontent.com/assets/3534596/19695375/37bda678-9aa0-11e6-89a5-59676856d4d7.png">

**Comment by kontur** [comment]
Thanks, this has already be fixed and will obviously not be visible in the next preview update.
