### ISSUE TITLE
font_size initial px: is not applied. 

### ISSUE THREAD

**Issue by DunwichType** [kontur/fontsampler-wordpress-plugin#22]
Initial size setting is shown in menus, but does not affect the text displayed.
<img width="312" alt="screen shot 2016-10-25 at 10 53 52 am" src="https://cloud.githubusercontent.com/assets/3534596/19695713/7959d9fc-9aa1-11e6-889a-e13f8024f655.png">

**Comment by kontur** [comment]
The latest 0.0.3 fixes this. In fact, line height and letter spacing suffered from the same shortcoming and are corrected as well.
