### ISSUE TITLE
Make unit fields text entry fields.

### ISSUE THREAD

**Issue by DunwichType** [kontur/fontsampler-wordpress-plugin#24]
The sliders used for units, in both the front end and back end, are not perfect. For example, I cannot get the “font_size initial px: ” slider to stop at 128px, only 127 or 129. Please allow text to be entered in these fields for setting precise values.

**Comment by kontur** [comment]
The 0.0.3 release has this suggestion implemented. Let me know what you think if you get around to testing it.

There's already a separate request for making the units (pixels, em, %) customisable as well and I am keen on getting that implemented as well.

**Comment by ncorso** [comment]
> The 0.0.3 release has this suggestion implemented. Let me know what you think if you get around to testing it.
> 
> There's already a separate request for making the units (pixels, em, %) customisable as well and I am keen on getting that implemented as well.

Hi @kontur, I stumble upon this response while looking for a way to change the tester's font size to EM. Is that level of customization available yet? Thanks in advance!

**Comment by kontur** [comment]
Hey @ncorso — nope, haven't gotten around to this little addition. I opened a separate issue for it.
