### ISSUE TITLE
Font dropdown selector only displays first font set.

### ISSUE THREAD

**Issue by DunwichType** [kontur/fontsampler-wordpress-plugin#25]
The dropdown selector for multiple fonts does not display all of the fonts in a sampler. It displays the first font set for each menu entry.
<img width="345" alt="screen shot 2016-10-25 at 11 10 17 am" src="https://cloud.githubusercontent.com/assets/3534596/19696262/a2a358f4-9aa3-11e6-8871-2975da5bbd6c.png">

**Comment by kontur** [comment]
I'll check into this. Might very well be that this is already fixed on the dev branch.

**Comment by kontur** [comment]
This was indeed in the 0.0.1 release but has been fixed since. 👍
