### ISSUE TITLE
Font samplers with multiple fonts only work as the first sampler. 

### ISSUE THREAD

**Issue by DunwichType** [kontur/fontsampler-wordpress-plugin#26]
A font sampler with multiple font sets will only work if it is the first sampler created (ID 1). Other samplers with multiple fonts sets display this error, even if they have the same configuration as ID 1.
“The typesampler with ID 4 can not be displayed because some files or the type sampler set are missing!”

**Comment by kontur** [comment]
Confirmed this bug was in the 0.0.1 release. It's been fixed in 0.0.2 and the latest 0.0.3 has this eliminated as well. Thanks for reporting.
