### ISSUE TITLE
Please add default font option to samplers

### ISSUE THREAD

**Issue by DunwichType** [kontur/fontsampler-wordpress-plugin#31]
The default font displayed in a sampler is the first font in the menu. Please add the option to choose other fonts. This could just be a checkbox next to each font that can only be active for a single font.

**Comment by kontur** [comment]
Makes sense, e.g. when you have a family sorted by weight but want the regular, not the thin displayed as first. 👍

**Comment by kontur** [comment]
This is implemented and will come live with the `0.0.4` release. Thanks again for the suggestion @DunwichType
