### ISSUE TITLE
Font sets & files needs to handle lots of entries better.

### ISSUE THREAD

**Issue by DunwichType** [kontur/fontsampler-wordpress-plugin#34]
The _Font sets & files_ page is going to get messy for sites that offer lots of fonts. Two ideas come to my mind:
- Group records into collapsible containers (like dropdown menus) . For example:
  Helvetica
      Helvetica Regular
      Helvetica Bold
- Manage them like pages. Let users assign categories to font records, and add a search bar to the _Font sets & files_ page.

**Comment by kontur** [comment]
Related to this also it becomes a performance issue to actually render a preview of all fonts used on those two pages, since presumably most are unique webfonts to be loaded in the browser.

**Comment by kontur** [comment]
MVP implementation of this limiting listing to 10 per page coming live with next release `0.0.5`
