### ISSUE TITLE
Allow overriding default font size per fontsampler

### ISSUE THREAD

**Issue by kontur** [kontur/fontsampler-wordpress-plugin#61]
Subissue of #3, but the most requested one.

**Comment by Vereschagin** [comment]
I can't find where to set the default font size for the sample text. Where is this set?

**Comment by kontur** [comment]
The font size UI option should have a "show more" option which has the default font size value. I suppose this would need to be made possible to set also without adding that UI element, will add as todo

**Comment by Vereschagin** [comment]
That would be the "Edit details" link? The changes I make don't stick. Make changes, save changes, go back to edit set, changes are gone and the sampler is using default values.

**Comment by kontur** [comment]
I'll get back to you on this one.

**Comment by Vereschagin** [comment]
If I change the settings via the Settings tab, which I take it actual means Default Settings, most settings seem to change. Changing settings in each fontsampler doesn't work.

**Comment by kontur** [comment]
Fix for this coming with the next release, which I'll publish shortly (together with a couple of other bug fixes)

**Comment by kontur** [comment]
Thanks for re-opening this. 0.2.4 should fix this. You can simple set a "initial" value even when the UI element is unchecked.
