### ISSUE TITLE
Https conflict

### ISSUE THREAD

**Issue by kontur** [kontur/fontsampler-wordpress-plugin#75]
Embeddding the Fontsampler on a https site will try to load the fonts via http, which causes a cross origin exception and prevents the fonts from loading.

**Comment by shahabsiavash** [comment]
My site is https and I didn't see that problem.

**Comment by kontur** [comment]
Thanks for sharing this info. This might have to do with some cross origin settings that may differ from host to host. I'll follow up after some testing.

**Comment by kontur** [comment]
I've tested and used the plugin on several https sites and not encountered any problems. Since the user originally reporting the issue has not provided more info I'll close this as "can't reproduce"
