### ISSUE TITLE
Deleting a Fontset with option to also remove files from Media Gallery

### ISSUE THREAD

**Issue by kontur** [kontur/fontsampler-wordpress-plugin#77]
Make Fontset delete either:
- Delete Fontset from Fontsampler
- Delete Fontset from Fontsampler and delete uploaded files from Media Gallery

**Comment by shahabsiavash** [comment]
Also if you edit a fontset to **change the font name** you have to upload the woff file again, otherwise it would be empty.

**Comment by kontur** [comment]
Hm, that seems like a bug. Thanks for reporting, I'll look into this as well
