### ISSUE TITLE
Non-Latin font names would be Unidentified

### ISSUE THREAD

**Issue by shahabsiavash** [kontur/fontsampler-wordpress-plugin#78]
I don't know it should be a bug or not, cause it only affects Non-Latin font names.

> By font name I don't mean the font name we create in the plugin but the font name that we assign to the font file in FontCreator for example.

Because the plugin automatically uses the font names for the dropdown and they are all Latin, I thought maybe I could change the font names (originals) to Persian, so they could be seen in Persian. But after that the plugin could not find the fonts because their names are Persian and it can't identify which font is which file. 

So if you have 2 fonts in a fontset, the loading is basically random and then it does not change. When you use F12 you can see that the font name in the styles is Unidentified. 

I hope I was be able to explain it correctly.

The best thing I guess is to create an option for user to choose between original font name or custom plugin font name when they are making a fontset. The custom name is already there, just needs to be enabled.

Sorry for the long text, I hope it wasn't a TL;DR ;)

**Comment by kontur** [comment]
Thanks again for pointing out all these non-latin font issues you are finding, I appreciate it very much!

Like you suggested, the option to display either the "detected" name or a saved name would be useful - also for other use cases than this. So this is something I would like to implement either way.

However, in regard to your issue I am wondering why font names (in the font file) in non-latin are not working in the first place, and I have a suspicion/vague memory that the names generated in the dropdown widget simply use the font's default name, but that might not be set if the font name is given only in a non-latin script. 
Would it be possible for you to provide me with two example woff files where this happens (unified name & font name in the names table in farssi or other non-latin script) so I can test and reproduce this issue like you experience it? I will naturally treat the fonts confidential and won't share them anywhere nor use them anywhere except on my local machine, and after testing I delete them from my machine. If not it's no problem and I understand, otherwise please email them to hello@johannesneumeier.com

**Comment by shahabsiavash** [comment]
Yes, of course. I have sent the email. Thanks for your replies. :)

**Comment by kontur** [comment]
With the upcoming release font names will no longer be extracted from the files and their respective embedded postscript names, but instead the font name in the Fontsampler menu will be used. Assuming that your Wordpress database tables are set to use a charset that supports the charset your font names are assigned in, it will be possible to display any text whatsoever (in whatever language or script) as font name. Stay tuned for a release soon, would love to hear your feedback ;)

**Comment by shahabsiavash** [comment]
Thanks a lot. I'll be waiting for this. :)

**Comment by kontur** [comment]
Live now as update 0.3.3 -  let me know how that works out for your use case ;)

**Comment by shahabsiavash** [comment]
Thanks. I had 2 issues with the new update. First of all it works in the matter of showing the Persian name. It's great :)

But I had this:

`Error: Permission to write to /var/www/vhosts/shahabsiavash.com/httpdocs/wp-content/plugins/fontsampler/css/custom/fontsampler-interface-12.css denied. Failed to update styles
`

And also when I have a dropdown for 2 fonts and I change to the second one it doesn't apply to the text. I have tried with predefined texts and also typing in the field. Just the first font works. In the back-end although it is loaded and uploaded.

**Comment by kontur** [comment]
Hey,
I had to roll out a few consecutive patches yesterday because of some PHP 5 issues; can you just confirm you're on 0.3.3?

I can't reproduce the issue with the dropdowns. For me these variations work: More than two font dropdown with at least one having a custom name, two font dropdown with at least having a custom name, only one font. Are you're fonts all having only woff, and no woff2? If you are unsure (woff2 is now hidden until its fully implemented in Opentype.js) try recreate the Fontset with just a woff and try selecting that one in the Fontsampler.

As per the permissions issue; that _should_ have actually gotten fixed with the update. Can you make sure to deep-refresh / clear browser cache and try reload the page. Does this message appear on the main page, or only in the backend when trying to save a Fontsampler with custom options? Do you know how to check what folder permissions this folder has, and if so, can you tell me: /wp-content/plugins/fontsampler/css/custom

**Comment by kontur** [comment]
Please try again with patch 0.3.5 for a fix for the permissions check error message :)

**Comment by shahabsiavash** [comment]
Thanks for your support and reply :)
I did upgrade it to 0.3.5 and now the CSS problem is solved. But the fonts that are not loaded is still there. I mean the second font and also the Basic, Features and Styling don't open when I click on them. Interface layout is fixed and just one row. Columns don't work either.

**Comment by kontur** [comment]
It sounds like there might be some Javascript errors preventing script execution (of other scripts) after them, not necessarily caused by Fontsampler even, but possibly. Do you know how to check the developer tools console logs in your browser? Can you find any errors there, or do you have a link to an online preview of the page this happens on? Obviously I can't check out the backend, but those Accordion elements not opening up sounds very much like a Javascript error preventing consecutive Javascript execution.

**Comment by shahabsiavash** [comment]
It was ok in 0.3.3 version. And I didn't do anything in the mean time. Yes, this is the error that developer tools show:

`Uncaught Error: Mismatched anonymous define() module: function (){"use strict";function a(a,b){if(!a||!a.nodeType||1!==a.nodeType)throw"Sortable: `el` must be HTMLElement, and not "+{}.toString.call(a);this.el=a,this.options=b=r({},b),a[L]=this;var c={group:Math.random(),sort:!0,disabled:!1,store:null,handle:null,scroll:!0,scrollSensitivity:30,scrollSpeed:10,draggable:/[uo]l/i.test(a.nodeName)?"li":">*",ghostClass:"sortable-ghost",chosenClass:"sortable-chosen",ignore:"a, img",filter:null,animation:0,setData:function(a,b){a.setData("Text",b.textContent)},dropBubble:!1,dragoverBubble:!1,dataIdAttr:"data-id",delay:0,forceFallback:!1,fallbackClass:"sortable-fallback",fallbackOnBody:!1};for(var d in c)!(d in b)&&(b[d]=c[d]);V(b);for(var f in this)"_"===f.charAt(0)&&(this[f]=this[f].bind(this));this.nativeDraggable=b.forceFallback?!1:P,e(a,"mousedown",this._onTapStart),e(a,"touchstart",this._onTapStart),this.nativeDraggable&&(e(a,"dragover",this),e(a,"dragenter",this)),T.push(this._onDragOver),b.store&&this.sort(b.store.get(this))}function b(a){v&&v.state!==a&&(h(v,"display",a?"none":""),!a&&v.state&&w.insertBefore(v,s),v.state=a)}function c(a,b,c){if(a){c=c||N,b=b.split(".");var d=b.shift().toUpperCase(),e=new RegExp("\\s("+b.join("|")+")(?=\\s)","g");do if(">*"===d&&a.parentNode===c||(""===d||a.nodeName.toUpperCase()==d)&&(!b.length||((" "+a.className+" ").match(e)||[]).length==b.length))return a;while(a!==c&&(a=a.parentNode))}return null}function d(a){a.dataTransfer&&(a.dataTransfer.dropEffect="move"),a.preventDefault()}function e(a,b,c){a.addEventListener(b,c,!1)}function f(a,b,c){a.removeEventListener(b,c,!1)}function g(a,b,c){if(a)if(a.classList)a.classList[c?"add":"remove"](b);else{var d=(" "+a.className+" ").replace(K," ").replace(" "+b+" "," ");a.className=(d+(c?" "+b:"")).replace(K," ")}}function h(a,b,c){var d=a&&a.style;if(d){if(void 0===c)return N.defaultView&&N.defaultView.getComputedStyle?c=N.defaultView.getComputedStyle(a,""):a.currentStyle&&(c=a.currentStyle),void 0===b?c:c[b];b in d||(b="-webkit-"+b),d[b]=c+("string"==typeof c?"":"px")}}function i(a,b,c){if(a){var d=a.getElementsByTagName(b),e=0,f=d.length;if(c)for(;f>e;e++)c(d[e],e);return d}return[]}function j(a,b,c,d,e,f,g){var h=N.createEvent("Event"),i=(a||b[L]).options,j="on"+c.charAt(0).toUpperCase()+c.substr(1);h.initEvent(c,!0,!0),h.to=b,h.from=e||b,h.item=d||b,h.clone=v,h.oldIndex=f,h.newIndex=g,b.dispatchEvent(h),i[j]&&i[j].call(a,h)}function k(a,b,c,d,e,f){var g,h,i=a[L],j=i.options.onMove;return g=N.createEvent("Event"),g.initEvent("move",!0,!0),g.to=b,g.from=a,g.dragged=c,g.draggedRect=d,g.related=e||b,g.relatedRect=f||b.getBoundingClientRect(),a.dispatchEvent(g),j&&(h=j.call(i,g)),h}function l(a){a.draggable=!1}function m(){R=!1}function n(a,b){var c=a.lastElementChild,d=c.getBoundingClientRect();return(b.clientY-(d.top+d.height)>5||b.clientX-(d.right+d.width)>5)&&c}function o(a){for(var b=a.tagName+a.className+a.src+a.href+a.textContent,c=b.length,d=0;c--;)d+=b.charCodeAt(c);return d.toString(36)}function p(a){var b=0;if(!a||!a.parentNode)return-1;for(;a&&(a=a.previousElementSibling);)"TEMPLATE"!==a.nodeName.toUpperCase()&&b++;return b}function q(a,b){var c,d;return function(){void 0===c&&(c=arguments,d=this,setTimeout(function(){1===c.length?a.call(d,c[0]):a.apply(d,c),c=void 0},b))}}function r(a,b){if(a&&b)for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}var s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J={},K=/\s+/g,L="Sortable"+(new Date).getTime(),M=window,N=M.document,O=M.parseInt,P=!!("draggable"in N.createElement("div")),Q=function(a){return a=N.createElement("x"),a.style.cssText="pointer-events:auto","auto"===a.style.pointerEvents}(),R=!1,S=Math.abs,T=([].slice,[]),U=q(function(a,b,c){if(c&&b.scroll){var d,e,f,g,h=b.scrollSensitivity,i=b.scrollSpeed,j=a.clientX,k=a.clientY,l=window.innerWidth,m=window.innerHeight;if(z!==c&&(y=b.scroll,z=c,y===!0)){y=c;do if(y.offsetWidth<y.scrollWidth||y.offsetHeight<y.scrollHeight)break;while(y=y.parentNode)}y&&(d=y,e=y.getBoundingClientRect(),f=(S(e.right-j)<=h)-(S(e.left-j)<=h),g=(S(e.bottom-k)<=h)-(S(e.top-k)<=h)),f||g||(f=(h>=l-j)-(h>=j),g=(h>=m-k)-(h>=k),(f||g)&&(d=M)),(J.vx!==f||J.vy!==g||J.el!==d)&&(J.el=d,J.vx=f,J.vy=g,clearInterval(J.pid),d&&(J.pid=setInterval(function(){d===M?M.scrollTo(M.pageXOffset+f*i,M.pageYOffset+g*i):(g&&(d.scrollTop+=g*i),f&&(d.scrollLeft+=f*i))},24)))}},30),V=function(a){var b=a.group;b&&"object"==typeof b||(b=a.group={name:b}),["pull","put"].forEach(function(a){a in b||(b[a]=!0)}),a.groups=" "+b.name+(b.put.join?" "+b.put.join(" "):"")+" "};return a.prototype={constructor:a,_onTapStart:function(a){var b=this,d=this.el,e=this.options,f=a.type,g=a.touches&&a.touches[0],h=(g||a).target,i=h,k=e.filter;if(!("mousedown"===f&&0!==a.button||e.disabled)&&(h=c(h,e.draggable,d))){if(D=p(h),"function"==typeof k){if(k.call(this,a,h,this))return j(b,i,"filter",h,d,D),void a.preventDefault()}else if(k&&(k=k.split(",").some(function(a){return a=c(i,a.trim(),d),a?(j(b,a,"filter",h,d,D),!0):void 0})))return void a.preventDefault();(!e.handle||c(i,e.handle,d))&&this._prepareDragStart(a,g,h)}},_prepareDragStart:function(a,b,c){var d,f=this,h=f.el,j=f.options,k=h.ownerDocument;c&&!s&&c.parentNode===h&&(G=a,w=h,s=c,t=s.parentNode,x=s.nextSibling,F=j.group,d=function(){f._disableDelayedDrag(),s.draggable=!0,g(s,f.options.chosenClass,!0),f._triggerDragStart(b)},j.ignore.split(",").forEach(function(a){i(s,a.trim(),l)}),e(k,"mouseup",f._onDrop),e(k,"touchend",f._onDrop),e(k,"touchcancel",f._onDrop),j.delay?(e(k,"mouseup",f._disableDelayedDrag),e(k,"touchend",f._disableDelayedDrag),e(k,"touchcancel",f._disableDelayedDrag),e(k,"mousemove",f._disableDelayedDrag),e(k,"touchmove",f._disableDelayedDrag),f._dragStartTimer=setTimeout(d,j.delay)):d())},_disableDelayedDrag:function(){var a=this.el.ownerDocument;clearTimeout(this._dragStartTimer),f(a,"mouseup",this._disableDelayedDrag),f(a,"touchend",this._disableDelayedDrag),f(a,"touchcancel",this._disableDelayedDrag),f(a,"mousemove",this._disableDelayedDrag),f(a,"touchmove",this._disableDelayedDrag)},_triggerDragStart:function(a){a?(G={target:s,clientX:a.clientX,clientY:a.clientY},this._onDragStart(G,"touch")):this.nativeDraggable?(e(s,"dragend",this),e(w,"dragstart",this._onDragStart)):this._onDragStart(G,!0);try{N.selection?N.selection.empty():window.getSelection().removeAllRanges()}catch(b){}},_dragStarted:function(){w&&s&&(g(s,this.options.ghostClass,!0),a.active=this,j(this,w,"start",s,w,D))},_emulateDragOver:function(){if(H){if(this._lastX===H.clientX&&this._lastY===H.clientY)return;this._lastX=H.clientX,this._lastY=H.clientY,Q||h(u,"display","none");var a=N.elementFromPoint(H.clientX,H.clientY),b=a,c=" "+this.options.group.name,d=T.length;if(b)do{if(b[L]&&b[L].options.groups.indexOf(c)>-1){for(;d--;)T[d]({clientX:H.clientX,clientY:H.clientY,target:a,rootEl:b});break}a=b}while(b=b.parentNode);Q||h(u,"display","")}},_onTouchMove:function(b){if(G){a.active||this._dragStarted(),this._appendGhost();var c=b.touches?b.touches[0]:b,d=c.clientX-G.clientX,e=c.clientY-G.clientY,f=b.touches?"translate3d("+d+"px,"+e+"px,0)":"translate("+d+"px,"+e+"px)";I=!0,H=c,h(u,"webkitTransform",f),h(u,"mozTransform",f),h(u,"msTransform",f),h(u,"transform",f),b.preventDefault()}},_appendGhost:function(){if(!u){var a,b=s.getBoundingClientRect(),c=h(s),d=this.options;u=s.cloneNode(!0),g(u,d.ghostClass,!1),g(u,d.fallbackClass,!0),h(u,"top",b.top-O(c.marginTop,10)),h(u,"left",b.left-O(c.marginLeft,10)),h(u,"width",b.width),h(u,"height",b.height),h(u,"opacity","0.8"),h(u,"position","fixed"),h(u,"zIndex","100000"),h(u,"pointerEvents","none"),d.fallbackOnBody&&N.body.appendChild(u)||w.appendChild(u),a=u.getBoundingClientRect(),h(u,"width",2*b.width-a.width),h(u,"height",2*b.height-a.height)}},_onDragStart:function(a,b){var c=a.dataTransfer,d=this.options;this._offUpEvents(),"clone"==F.pull&&(v=s.cloneNode(!0),h(v,"display","none"),w.insertBefore(v,s)),b?("touch"===b?(e(N,"touchmove",this._onTouchMove),e(N,"touchend",this._onDrop),e(N,"touchcancel",this._onDrop)):(e(N,"mousemove",this._onTouchMove),e(N,"mouseup",this._onDrop)),this._loopId=setInterval(this._emulateDragOver,50)):(c&&(c.effectAllowed="move",d.setData&&d.setData.call(this,c,s)),e(N,"drop",this),setTimeout(this._dragStarted,0))},_onDragOver:function(a){var d,e,f,g=this.el,i=this.options,j=i.group,l=j.put,o=F===j,p=i.sort;if(void 0!==a.preventDefault&&(a.preventDefault(),!i.dragoverBubble&&a.stopPropagation()),I=!0,F&&!i.disabled&&(o?p||(f=!w.contains(s)):F.pull&&l&&(F.name===j.name||l.indexOf&&~l.indexOf(F.name)))&&(void 0===a.rootEl||a.rootEl===this.el)){if(U(a,i,this.el),R)return;if(d=c(a.target,i.draggable,g),e=s.getBoundingClientRect(),f)return b(!0),void(v||x?w.insertBefore(s,v||x):p||w.appendChild(s));if(0===g.children.length||g.children[0]===u||g===a.target&&(d=n(g,a))){if(d){if(d.animated)return;r=d.getBoundingClientRect()}b(o),k(w,g,s,e,d,r)!==!1&&(s.contains(g)||(g.appendChild(s),t=g),this._animate(e,s),d&&this._animate(r,d))}else if(d&&!d.animated&&d!==s&&void 0!==d.parentNode[L]){A!==d&&(A=d,B=h(d),C=h(d.parentNode));var q,r=d.getBoundingClientRect(),y=r.right-r.left,z=r.bottom-r.top,D=/left|right|inline/.test(B.cssFloat+B.display)||"flex"==C.display&&0===C["flex-direction"].indexOf("row"),E=d.offsetWidth>s.offsetWidth,G=d.offsetHeight>s.offsetHeight,H=(D?(a.clientX-r.left)/y:(a.clientY-r.top)/z)>.5,J=d.nextElementSibling,K=k(w,g,s,e,d,r);if(K!==!1){if(R=!0,setTimeout(m,30),b(o),1===K||-1===K)q=1===K;else if(D){var M=s.offsetTop,N=d.offsetTop;q=M===N?d.previousElementSibling===s&&!E||H&&E:N>M}else q=J!==s&&!G||H&&G;s.contains(g)||(q&&!J?g.appendChild(s):d.parentNode.insertBefore(s,q?J:d)),t=s.parentNode,this._animate(e,s),this._animate(r,d)}}}},_animate:function(a,b){var c=this.options.animation;if(c){var d=b.getBoundingClientRect();h(b,"transition","none"),h(b,"transform","translate3d("+(a.left-d.left)+"px,"+(a.top-d.top)+"px,0)"),b.offsetWidth,h(b,"transition","all "+c+"ms"),h(b,"transform","translate3d(0,0,0)"),clearTimeout(b.animated),b.animated=setTimeout(function(){h(b,"transition",""),h(b,"transform",""),b.animated=!1},c)}},_offUpEvents:function(){var a=this.el.ownerDocument;f(N,"touchmove",this._onTouchMove),f(a,"mouseup",this._onDrop),f(a,"touchend",this._onDrop),f(a,"touchcancel",this._onDrop)},_onDrop:function(b){var c=this.el,d=this.options;clearInterval(this._loopId),clearInterval(J.pid),clearTimeout(this._dragStartTimer),f(N,"mousemove",this._onTouchMove),this.nativeDraggable&&(f(N,"drop",this),f(c,"dragstart",this._onDragStart)),this._offUpEvents(),b&&(I&&(b.preventDefault(),!d.dropBubble&&b.stopPropagation()),u&&u.parentNode.removeChild(u),s&&(this.nativeDraggable&&f(s,"dragend",this),l(s),g(s,this.options.ghostClass,!1),g(s,this.options.chosenClass,!1),w!==t?(E=p(s),E>=0&&(j(null,t,"sort",s,w,D,E),j(this,w,"sort",s,w,D,E),j(null,t,"add",s,w,D,E),j(this,w,"remove",s,w,D,E))):(v&&v.parentNode.removeChild(v),s.nextSibling!==x&&(E=p(s),E>=0&&(j(this,w,"update",s,w,D,E),j(this,w,"sort",s,w,D,E)))),a.active&&((null===E||-1===E)&&(E=D),j(this,w,"end",s,w,D,E),this.save())),w=s=t=u=x=v=y=z=G=H=I=E=A=B=F=a.active=null)},handleEvent:function(a){var b=a.type;"dragover"===b||"dragenter"===b?s&&(this._onDragOver(a),d(a)):("drop"===b||"dragend"===b)&&this._onDrop(a)},toArray:function(){for(var a,b=[],d=this.el.children,e=0,f=d.length,g=this.options;f>e;e++)a=d[e],c(a,g.draggable,this.el)&&b.push(a.getAttribute(g.dataIdAttr)||o(a));return b},sort:function(a){var b={},d=this.el;this.toArray().forEach(function(a,e){var f=d.children[e];c(f,this.options.draggable,d)&&(b[a]=f)},this),a.forEach(function(a){b[a]&&(d.removeChild(b[a]),d.appendChild(b[a]))})},save:function(){var a=this.options.store;a&&a.set(this)},closest:function(a,b){return c(a,b||this.options.draggable,this.el)},option:function(a,b){var c=this.options;return void 0===b?c[a]:(c[a]=b,void("group"===a&&V(c)))},destroy:function(){var a=this.el;a[L]=null,f(a,"mousedown",this._onTapStart),f(a,"touchstart",this._onTapStart),this.nativeDraggable&&(f(a,"dragover",this),f(a,"dragenter",this)),Array.prototype.forEach.call(a.querySelectorAll("[draggable]"),function(a){a.removeAttribute("draggable")}),T.splice(T.indexOf(this._onDragOver),1),this._onDrop(),this.el=a=null}},a.utils={on:e,off:f,css:h,find:i,is:function(a,b){return!!c(a,b,a)},extend:r,throttle:q,closest:c,toggleClass:g,index:p},a.create=function(b,c){return new a(b,c)},a.version="1.4.2",a}
http://requirejs.org/docs/errors.html#mismatch
    at makeError (require.js:17)
    at intakeDefines (require.js:81)
    at require.js:104`

And here you can see the live version. It is a test, so it is private. So please use this password: **fntsmplr**
[https://shahabsiavash.com/?p=2658](https://shahabsiavash.com/?p=2658)

I think you are not be able to write Persian, so you may wanna use the sample texts.

**Comment by kontur** [comment]
Okay, this confirms my suspicions. I used a library for module loading that has caused problems in the past, but I tried to move it to the bottom of the page then and it seemed to solve the issue. The link you supplied redirects me to https://shahabsiavash.com/%D8%AA%D8%B3%D8%AA-%D9%86%D9%85%D8%A7%DB%8C%D8%B4-%D9%81%D9%88%D9%86%D8%AA/ without password request - also not surprising, no errors there.

Unless you have a ton in use or don't want to share that info, can you let me know what other plugins you use? Did you install any other plugins recently, which might explain why it "appears" to have come with the 0.3.3 update? I'm fairly certain this is a case of two different plugins declaring a module loader, and one interfering with the other.

**Comment by shahabsiavash** [comment]
Oh! So you're telling me that you didn't see this? So it must be a bug in a password-protected posts.
![pass](https://user-images.githubusercontent.com/20119395/28616912-b21fe3e0-7213-11e7-8451-f52449d8466f.jpg)

If you saw that, you can put the pass into that field and press the purple button.

No. it's not a ton :) I remember the only plugin that has been updated in a few days ago was **Contact Form 7.**

_Comments - wpDiscuz
Contact Form 7
Easy Testimonials
Friends Link Widget
Google Authenticator
Inline Related Posts
Really Simple SSL
Social Icons Widget by WPZOOM
UpdraftPlus - Backup/Restore
WP User Avatar
JetPack by WordPress.com
Jalali WP_

**Comment by kontur** [comment]
Thanks for providing the extra info. I've opened #109 to separate this issue. I can't reproduce the error on the user facing side, but having, for example, "Comments - wpDiscuz" installed, activated, and then browsing to the Fontsampler admin page will cause this error.

As I suspected, this is something I've encountered before, and attempted to fix once, but it's a bit of a tricky issue. Basically any plugin can include and javascript libraries they want, and both include a requirejs module loader - which is good, only that requirejs never expects to be present on any page twice (i.e. it is loaded once, then loads other scripts). I've been for a while wanting to compile and bundle Fontsampler scripts better and more "interference"-free; so this is a good reason to have a look into this.

Are you getting this error also on user-facing pages? I might not be getting this error outside the admin area, because although I now have the plugins you do, not all of them might actually be loading or configured right - and interfering - on my test site's user-facing portion.

**Comment by kontur** [comment]
@shahabsiavash A fix for #109 has just shipped with 0.3.7 - let me know if you still get errors on the Fontsampler admin page after updating. :)

**Comment by shahabsiavash** [comment]
Thanks. I will check that and wrote back here :)

**Comment by shahabsiavash** [comment]
Sorry for the delay. I have to say it is fixed for me. Although it uses the Fontsampler font names only there is more than 1 font and therefore a dropdown menu. 
![image](https://user-images.githubusercontent.com/20119395/32129955-aa4d9dac-bb9b-11e7-977b-d62de94ae4f2.png)

If there is only 1 font (and basically no dropdown) then it is still the original font name.

An unrelated question: Is there a way that I could change the "Select a sample text" phrase? It's English and I want it to be Persian. Is there a translation file for this plugin?

Thanks a lot,

**Comment by kontur** [comment]
Okay, I'll have a look into why the chosen name does not get overwritten when it is a single font and no dropdown. Reopening this issue until this, too, is fixed.

I'll open a new issue for the basic translation of the plugin. I've been meaning to implement this for a while now 👍

**Comment by shahabsiavash** [comment]
Thanks a lot. :)

**Comment by kontur** [comment]
I can't confirm this. Form my tests both single font and multiple font Fontsamplers with non-latin fonts display the font name correctly as set in the admin area - in the sense that you can overwrite or use the detected font name when uploading the font.

To change (overwrite to either a ascii based name or a non-latin name) use the Fonts tab - the font name is set per-font. Can you show an example and describe exactly:
- What you do
- What you expect to happen
- What actually happens

Thanks again for being so active providing feedback! Let's see what's going on with this issue 👍

**Comment by shahabsiavash** [comment]
This is solved too. I don't know what happened before. Maybe I forgot to change one! Sorry for the trouble. Now it works :)
