### ISSUE TITLE
SQL query displayed in plugin settings

### ISSUE THREAD

**Issue by drawcard** [kontur/fontsampler-wordpress-plugin#8]
It looks as though an SQL query is being printed out in the FontSampler plugin (this occurred after clicking "Edit" to change the settings of a font sample). 

![image](https://cloud.githubusercontent.com/assets/1435638/19297719/2744f208-908f-11e6-9079-b989e3b02cf4.png)

![image](https://cloud.githubusercontent.com/assets/1435638/19297740/5cd318fa-908f-11e6-9818-2d23e68849e4.png)

**Comment by drawcard** [comment]
Also appears on the frontend too:

![image](https://cloud.githubusercontent.com/assets/1435638/19297912/9f3b8924-9090-11e6-988b-95828ea4f479.png)

**Comment by kontur** [comment]
Forgot some debug queries in there, my bad. Not bumping the version, but the master has them removed now.
