### ISSUE TITLE
Fonts not displaying

### ISSUE THREAD

**Issue by Vereschagin** [kontur/fontsampler-wordpress-plugin#84]
Hi, Johannes:

Although the fonts are uploaded and residing in my uploads folder, they are not being displayed in Fontsampler and do not appear in the font selector. Fontsampler seems to be using random variations on the default body fonts. In this screenshot, Fontsampler should be using the Toronto Subway fonts that appear in the head and the page title.

![chrome screen shot 2017-04-18 at 9 59 28 am](https://cloud.githubusercontent.com/assets/10108357/25136116/120ae326-2422-11e7-9b6d-12293159c09a.png)

**Comment by kontur** [comment]
Just to be sure, when you log in to the Fontsampler admin area, do you get a "Notifications" tab at the top alerting you of any issues?
Are you sure the "Fontsets" have names associated with them? I think I was a bit too lax with detecting when they are missing names (and preventing saving then), so it might be that when a Fontsampler has Fontsets that are not given a name they won't display.
Other than that, this could be related to #83 you reported earlier, so solving that one might affect this issue as well.

**Comment by Vereschagin** [comment]
No, there is no Notifications tab. Yes, the font sets all have names.

**Comment by kontur** [comment]
As pointed out in #83, this is due to the font file missing font family table entries.
