### ISSUE TITLE
Custom size setting for individual fontsampler with size UI doesn't honor set size

### ISSUE THREAD

**Issue by kontur** [kontur/fontsampler-wordpress-plugin#97]
But uses default instead.

**Comment by Vereschagin** [comment]
It doesn't honour the initial size set in the default settings, tab, either. I have both set for 36px for initial display. The fontsampler still uses 40px as the initial size.

**Comment by kontur** [comment]
Thanks for commenting. I have just implemented a fix for this, merely bundling a few more other issues into the update before releasing the update, so people don't get spammed with plugin updates too much. Shipping this either today or later in the week.

This was a problem resulting from various combinations of using default size, using size UI elements and using custom sizes but no size UI element.
